vich_uploader:
    db_driver: orm

    mappings:
        animaux_image:
            uri_prefix: /img/animaux
            upload_destination: '%kernel.project_dir%/public/img/animaux'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

